### ISSUE TITLE
run 报错

### ISSUE THREAD

**Issue by xgzl87** [meibin08/react-redux-chat#1]
> react-redux-chat@1.0.0 dev F:\learning\react-redux-chat-master
> cross-env NODE_ENV=development webpack-dev-server --inline

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8085
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-redux-chat@1.0.0 dev: `cross-env NODE_ENV=development webpack-dev-server --inline`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-chat@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by xgzl87** [comment]
代理问题

**Comment by meibin08** [comment]
Hi，请按README.md文件操作，
请确保是否已安装nodejs，如有疑问建议进群@，截图交流，能更快速解决问题，感谢！

发自我的 iPhone
